### ISSUE TITLE
Introduce an alternative to template_redirect for cache plugins

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wordpress-develop#70]
Details to be added/discussed with @Tabrisrp

**Comment by remyperona** [comment]
There is an initiative in Gutenberg to add this to core: https://github.com/WordPress/gutenberg/pull/61212

**Comment by MathieuLamiot** [comment]
Thanks!
Is there any way we could contribute here? Maybe reviewing the PR on Gutenberg / testing it? Or maybe bridging the gap from the Gutenberg PR into WordPress core https://core.trac.wordpress.org/ticket/43258 as suggested in the comments of the PR?

```
 * This is a hack which would eventually be replaced with something like this in wp-includes/template-loader.php:
 *
 *          $template = apply_filters( 'template_include', $template );
 *     +    ob_start( 'wp_template_output_buffer_callback' );
 *          if ( $template ) {
 *              include $template;
 *          } elseif ( current_user_can( 'switch_themes' ) ) {
 *
 * @link https://core.trac.wordpress.org/ticket/43258
```

**Comment by MathieuLamiot** [comment]
As discussed, not much to be doe here since it's already on-going with Gutenberg and people involved in WP Core. We'll keep an eye on this to eventually leverage it in WP Rocket once in WP Core.
